# Simulations for DNA circuits with Python3
## Part II Libraries used in simulations
This part will introduce the libraries(modules) and the functions may be used in the simulations. For more details, you can refer to the official docs: [numpy & scipy](https://docs.scipy.org/doc/) [pandas](http://pandas.pydata.org/pandas-docs/stable/) [matplotlib](https://matplotlib.org/contents.html)

### 2.1 Modules
Python module is the highest-level program organization unit, which packages program code and data for reuse, and provides self-contained namespaces that minimize variable name clashes across your programs. In concrete terms, modules typically correspond to Python program files. Each file is a module, and modules import other modules to use the names they define. 

Python modules are easy to create; they're just files of Python program code created with a text editor. You don't need to write special syntax to tell Python you're making a module; almost any text file will do. Because Python handles all the details of finding and loading modules, modules are also easy to use; clients simply import a module, or specific names a module defines, and use the objects they reference.

#### 2.1.1 Module Creation
To define a module, simply use your text editor to type some Python code into a text file, and save it with a “.py” extension; any such file is automatically considered a Python module. All the names assigned at the top level of the module become its attributes (names associated with the module object) and are exported for clients to use—they morph from variable to module object attribute automatically.

For instance, if you type the following def into a file called module1.py and import it, you create a module object with one attribute—the name printer , which happens to be a reference to a function object:

``` python
def printer(x):        # Module attribute
    print(x)
```


#### 2.1.2 Module Usage
Clients can use the simple module file we just wrote by running an **import** or **from** statement. Both statements find, compile, and run a module file's code, if it hasn't yet been loaded. The chief difference is that **import** fetches the module as a whole, so you must qualify to fetch its names; in contrast, **from** fetches (or copies) specific names out of the module.

Let's see what this means in terms of code. All of the following examples wind up calling the printer function defined in the prior section's module1.py module file, but in different ways.

##### The import Statement
In the first example, the name **module1** serves two different purposes—it identifies an external file to be loaded, and it becomes a variable in the script, which references the module object after the file is loaded:

In [1]:
import module1                         # Get module as a whole (one or more)
module1.printer('Hello world!')        # Qualify to get names

Hello world!


The import statement simply lists one or more names of modules to load, separated by commas. Because it gives a name that refers to the whole module object, we must go through the module name to fetch its attributes (e.g., module1.printer ).

##### The from Statement
By contrast, because from copies specific names from one file over to another scope, it allows us to use the copied names directly in the script without going through the module (e.g., printer):

In [1]:
from module1 import printer
printer('Hello world!')

Hello world!


This form of **from** allows us to list one or more names to be copied out, separated by commas. Here, it has the same effect as the prior example, but because the imported name is copied into the scope where the from statement appears, using that name in the script requires less typing—we can use it directly instead of naming the enclosing module. In fact, we must; **from** doesn’t assign the name of the module itself.

##### The from * Statement
Finally, the next example uses a special form of from : when we use a * instead of specific names, we get copies of all names assigned at the top level of the referenced module. Here again, we can then use the copied name printer in our script without going through the module name:

In [2]:
from module1 import *        # Copy out _all_ variables
printer('Hello world!')

Hello world!


### 2.2 NumPy
NumPy’s main object is the homogeneous multidimensional array. It is a table of elements (usually numbers), all of the same type, indexed by a tuple of positive integers.

#### 2.2.1 Matrices in NumPy
In standard python, **list** is used to store a series of values, but it suffers from the lack of the functions dealing with multidimensional arrays. This problem is addressed in NumPy.

To create a matrix below, you may use **numpy.array** or **numpy.asarray** to convert **lists** into **matrix**:

$
 \begin{bmatrix}
   1 & 2 & 3 \\
   4 & 5 & 6 \\
   7 & 8 & 9
  \end{bmatrix} %\tag{4}
$

In [2]:
import numpy as np        # of course firstly import numpy

L = [[1,2,3],[4,5,6],[7,8,9]]
M1 = np.array(L)
print('M1 = \n', M1)
M2 = np.asarray(L)
print('M2 = \n', M2)

M1 = 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
M2 = 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


The two functions both can produce matrices, and the only difference is that when the input is an matrix, the function **np.array** will make a copy whereas **np.asarray** will not.

Sometimes you may want to get a arithmetic progression， you can use **[numpy.linspace](https://docs.scipy.org/doc/numpy/user/quickstart.html)**:

``` python
numpy.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None)
```

##### parameters
**start : *scalar*** The starting value of the sequence.

**stop : *scalar*** The end value of the sequence, unless endpoint is set to False. In that case, the sequence consists of all but the last of num + 1 evenly spaced samples, so that stop is excluded. Note that the step size changes when endpoint is False.

**num : *int, optional*** Number of samples to generate. Default is 50. Must be non-negative.

##### returns
**samples : *ndarray*** There are num equally spaced samples in the closed interval [start, stop] or the half-open interval [start, stop) (depending on whether endpoint is True or False).

For example, to obtain 1 to 10:

In [6]:
V = np.linspace(1, 10, 10)
print(V)

[  1.   2.   3.   4.   5.   6.   7.   8.   9.  10.]


#### 2.2.2 Dimension of matrix
The dimension of a matrix can be read by accessing the attribute **shape**.

On the other hand, the dimension of a matrix can be changed via **numpy.reshape**:

In [8]:
M = np.array([[1,2,3],[4,5,6]])
print('M = \n', M)
print('The shape of M: ', M.shape)         # M is a 2 by 3 matrix
M1 = M.reshape(3, 2)
print('M1 = \n', M1)
print('The shape of M1: ', M1.shape)       # M1 is a 3 by 2 matrix

M = 
 [[1 2 3]
 [4 5 6]]
The shape of M:  (2, 3)
M1 = 
 [[1 2]
 [3 4]
 [5 6]]
The shape of M1:  (3, 2)


The dimension of a matrix may be changed via transposition. The transpose of matrix M is represented by M.T in NumPy:

In [3]:
M = np.array([[1,2,3],[4,5,6]])
print('M = \n', M)
print('M.T = \n', M.T)

M = 
 [[1 2 3]
 [4 5 6]]
M.T = 
 [[1 4]
 [2 5]
 [3 6]]


#### 2.2.3 Matrix functions
NumPy offers a lot of practical functions, including **np.dot**, **np.power** **np.sum** et al.

**np.dot** calculates the inner product of two matrices:

**np.power** calculates power power.

**np.sum** calculates the sum of two matrix along a designated axis.

In [15]:
A = np.array([2,0,2])
B = np.array([[0,1,0],[1,2,3]])
C = np.dot(A, B.T)
print('C = A·B = \n', C)
D = np.power(A, 3)
print('D = A * A * A = \n', D)
E = np.sum(B)
F = np.sum(B, axis=0)
G = np.sum(B, axis=1)
print('E = sum(B) = \n', E)
print('F = sum(B, axis=0) = \n', F)
print('G = sum(B, axis=1) = \n', G)

C = A·B = 
 [0 8]
D = A * A * A = 
 [8 0 8]
E = sum(B) = 
 7
F = sum(B, axis=0) = 
 [1 3 3]
G = sum(B, axis=1) = 
 [1 6]


### pandas